[SQUASH] Launcher3: Remove Protected apps in favour of system AppLock
Launcher: Remove Protected apps in favour of system AppLock

Signed-off-by: DennySPb <dennyspb@gmail.com>
Change-Id: Ie785da5f44389a87cb2a8a42a8e40f817fc72228

Launcher3: remove dangling comma

Remove protected apps in favor of system Applock commit
Ie785da5f44389a87cb2a8a42a8e40f817fc72228
left behind a dangling comma in db create cmd causing
SQLiteLog: (1) near ")": syntax error in "CREATE TABLE trust_apps(uid INTEGER PRIMARY KEY AUTOINCREMENT,pkgname TEXT,hidden INTEGER DEFAULT 0,)"

FATAL EXCEPTION: launcher-loader
Process: com.android.launcher3, PID: 20026
android.database.sqlite.SQLiteException: near ")": syntax error (code 1 SQLITE_ERROR): , while compiling: CREATE TABLE trust_apps(uid INTEGER PRIMARY KEY AUTOINCREMENT,pkgname TEXT,hidden INTEGER DEFAULT 0,)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1919)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1841)
	at com.android.launcher3.trust.db.TrustDatabaseHelper.onCreate(TrustDatabaseHelper.java:59)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:411)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
	at com.android.launcher3.trust.db.TrustDatabaseHelper.isPackageHidden(TrustDatabaseHelper.java:116)
	at com.android.launcher3.trust.HiddenAppsFilter.shouldShowApp(HiddenAppsFilter.java:38)
	at com.android.launcher3.model.AllAppsList.add(AllAppsList.java:135)
	at com.android.launcher3.model.LoaderTask.loadAllApps(LoaderTask.java:894)
	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:208)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)

Change-Id: Ie23f31d75ce88eee99e4114bb31e077185d724bd

Launcher: Restore biometric prompt for Hidden Apps

this was accidentally deleted with Protected apps removal

Signed-off-by: DennySPb <dennyspb@gmail.com>
Change-Id: I279c3981b796b4f2b9de375d68bf3a5539940418

Launcher: Allow to tap at whole item in Hidden Apps

since Protected apps were removed, we could be more user friendly
and should allow to change Hidden apps state by tapping on app label and icon

Change-Id: Ia69ec502141d6969241be972be5dc6f2a7f17079
Signed-off-by: DennySPb <dennyspb@gmail.com>